# 👤 담당: 노대영 (DB 설정)
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080
